name=input("enter your name ")
age=int(input("enter your age "))
city=input("enter your city name ")
college=input("enter your college name ")
branch = input("Enter your branch: ")
career_goal = inpur("enter your goal; ")
print("\n----- STUDENT PROFILE -----")
print("Name:", name)
print("Age:", age)
print("City:", city)
print("College:", college)
print("Branch:", branch)
print("Career Goal:", career_goal)
